### PR TITLE
Ordering by RCA issue #220

### LINKED ISSUE #220: support for ordering results by RCA
The idea here is to add support for sorting results for endpoints returning RCA. Currently I am getting the following error:
```
"sort Measure(\"Trade Value RCA\") not found in measures"
```

Here is a sample URL: https://api.oec.world/tesseract/data.jsonrecords?cube=trade_i_baci_a_92&Exporter+Country=sapry&time=year.latest&drilldowns=Year&measures=Trade+Value&parents=true&rca=Exporter+Country,HS4,Trade+Value&sparse=false&limit=3&sort=Trade+Value+RCA.desc

I need this for a bar chart of top exports by RCA where i only want to show the top 10 and it would be inefficient to retrieve all results and sort them client-side.

### PR DESCRIPTION
**Pull request by Jayrmajithia**
Solves the issue of ordering by RCA

closes #220

### CODE REVIEW

File: tesseract-core/src/lib.rs [hunk 1]
```diff
@@ -654,15 +654,24 @@ impl Schema {
 
         let sort = if let Some(ref s) = query.sort {
             // sort column needs to be named by alias
-            let sort_column = query.measures.iter()
-                .position(|m| m == &s.measure)
-                .ok_or_else(|| format_err!("sort {:?} not found in measures", &s.measure))?;
+            // Checking if we are going to sort by RCA or not
+            let measure_name = &s.measure.to_string();
+            if measure_name.contains("RCA") {
```
Comment (jspeis) [inline tesseract-core/src/lib.rs]: The only thing I wonder is, should we do a more specific check here that the sort is some form of "<Column> RCA"? because now if you did `sort=Blah RCA` it would catch it even if it's not an actual column. It might just help avoid future issue in case someone has a column named like `RCAP` and they want to sort on that

Comment (Jayrmajithia) [reply tesseract-core/src/lib.rs]: Will take a look at it

File: tesseract-core/src/lib.rs [hunk 2]
```diff
@@ -655,12 +655,24 @@ impl Schema {
...
             // Checking if we are going to sort by RCA or not
-            let measure_name = &s.measure.to_string();
-            if measure_name.contains("RCA") {
-                Some(SortSql {
-                    direction: s.direction.clone(),
-                    column: format!("rca"),
-                })
+            let measure_name = s.measure.to_string();
+            if let Some(ref rca) = query.rca {
+                if measure_name == format!("{} RCA", rca.mea.clone().to_string()){
```
Comment (jspeis) [inline tesseract-core/src/lib.rs]: do we need `clone()` & `to_string()` here? can we just use `to_string()`?

Comment (Jayrmajithia) [reply tesseract-core/src/lib.rs]: Yep we don't need it I added by mistake

File: tesseract-core/src/lib.rs [hunk 3]
```diff
@@ -655,12 +655,24 @@ impl Schema {
...
+                    Some(SortSql {
+                        direction: s.direction.clone(),
+                        column: format!("rca"),
+                    })
+                } else {
```
Comment (jspeis) [inline tesseract-core/src/lib.rs]: would we be able to potentially avoid duplicating this `else` block by converting the nested `if`s into a single compound if statement e.g. `if X && Y ` instead of `if X { if Y { ...` ... ?

File: tesseract-core/src/lib.rs [hunk 4]
```diff
@@ -657,7 +657,7 @@ impl Schema {
             // Checking if we are going to sort by RCA or not
             let measure_name = s.measure.to_string();
             if let Some(ref rca) = query.rca {
-                if measure_name == format!("{} RCA", rca.mea.clone().to_string()){
+                if measure_name == format!("{} RCA", rca.mea.to_string()){
```
Comment (jspeis) [inline tesseract-core/src/lib.rs]: since this is in the context of a format! , do we even need to the to_string()? Might be able to remove that too?

File: tesseract-core/src/lib.rs (hunk 3 above)
Comment (Jayrmajithia) [reply tesseract-core/src/lib.rs]: We cannot because I need to get the column name of mea inside the RCA

File: tesseract-core/src/lib.rs (hunk 4 above)
Comment (Jayrmajithia) [reply tesseract-core/src/lib.rs]: We need to_string because the rca.mea is of format measure

File: tesseract-core/src/lib.rs (hunk 3 above)
Comment (jspeis) [reply tesseract-core/src/lib.rs]: In that case, could we maybe rewrite the `if` into a match?      like      ```match query.rca {
                Some(ref rca) => {

                },
                None =>
            }``` could that capture the flow while avoiding the duplication?

Comment (Jayrmajithia) [reply tesseract-core/src/lib.rs]: But we still need to duplicate it in a scenario when we have rca column and we perform a sort on something else that is not in the RCA column it won't work. The fix could be we Just first check if the sort.measure contains the  contains RCA in it or not and if contains we do a strict check

Comment (jspeis) [reply tesseract-core/src/lib.rs]: I guess I'm really averse to extra nesting and duplication so I'm trying to find a way around this :) thoughts about an approach like this?

```rust
            let rca_mea_name = if query.rca.is_some() {
                 query.rca.as_ref().unwrap().mea.to_string() 
            } else {
                "".to_string()
            };
            if measure_name == format!("{} RCA", rca_mea_name) {
                    Some(SortSql {
                        direction: s.direction.clone(),
                        column: "rca".to_string(),
                    })
            }
```

Does this work? What are your thoughts?

Comment (Jayrmajithia) [reply tesseract-core/src/lib.rs]: I like this idea because it has less complexity of nesting. This should work
